language: node_js
node_js:
  - "14"
sudo: required
services:
  - docker
before_script:
  - npm test
  - docker build -t back .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag back $DOCKER_USER/front:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/front:$TRAVIS_BUILD_NUMBER
  - docker tag back $DOCKER_USER/front:latest
  - docker push $DOCKER_USER/front:latest